name: 'retail_dwh'
version: '1.0.0'
config-version: 2

profile: 'retail_dwh'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  retail_dwh:
    # bronze:              # ЗАКОММЕНТИРОВАЛ
    #   +materialized: table
    #   +schema: bronze
    silver:
      +materialized: table
      +schema: silver  
    gold:
      +materialized: table
      +schema: gold