retail_dwh:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: airflow
      pass: airflow
      port: 5432
      dbname: dwh_raw
      schema: public
      threads: 4